services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=tracking'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5433:5432'
  redis:
    image: 'redis:latest'
    ports:
      - '6380:6379'
