spring:
  application:
    name: trackr
  flyway:
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    locations: classpath:db/migration
    clean-disabled: false
    enabled: true
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none

app:
  jwt:
    issuer: ${JWT_ISSUER}
    secret: ${JWT_SECRET}
    access-token-ttl: ${JWT_ACCESS_TOKEN_TTL}
    refresh-token-ttl: ${JWT_REFRESH_TOKEN_TTL}
    clock-skew-seconds: ${JWT_CLOCK_SKEW_SECONDS}

